version: '2'
services:
  serve:
    # we use image for faster developing with angular-boilerplate
    image: teracy/angular-boilerplate:dev
    command: ng serve --host 0.0.0.0
    environment:
      NODE_ENV: development
    volumes:
      - .:/home/app
      - /home/app/node_modules
    ports:
      - "4200:4200"
    # see: https://github.com/docker/compose/issues/2231#issuecomment-165137408
    #tty: true # problem: https://github.com/docker/compose/issues/3783

  # FIXME(hoatle): $ docker-compose up test should work repeatedly
  test:
    #build: .
    image: teracy/angular-boilerplate:dev
    command: ng test --browsers Chrome_no_sandbox
    environment:
      NODE_ENV: development
    volumes:
      - .:/home/app
      - /home/app/node_modules
    privileged: true # for Chrome to run on Docker
    # see: https://github.com/docker/compose/issues/2231#issuecomment-165137408
    #tty: true # problem: https://github.com/docker/compose/issues/3783
